spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWOD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      